version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: "/work"
    ports:
      - 8000:8000
    volumes:
      - ./:/work
    tty: true
    user: "vscode"
